#pragma once

#include <Arduino.h>

#define BTN_CALIBRATE_PIN P1_11
#define BTN_TERMINATE_PIN P1_12
#define BTN_PAUSEEXEC_PIN P1_15

#define G_IN_MS2 9.8066

#define SAMPLING_RATE 20.0
#define SAMPLES 64
#define BUFFER_WINDOW_SIZE 16
#define BUFFER_WINDOW_OFFSET (SAMPLES - BUFFER_WINDOW_SIZE)
#define DETECTION_THS (1.0 * G_IN_MS2)

typedef enum
{
    MDC_WALKING,
    MDC_STANDING,
    MDC_SITTING,
    MDC_LAYING_B,
    MDC_LAYING_F,
    MDC_LAYING_L,
    MDC_LAYING_R
} MDC_STATE;